import {newArrOne} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },

];
// =================== NavBarList End here ======================
// =================== Furniture data Start here ============
export const Furniture = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/61fhKEee3JL._SX522_.jpg",
    productName: "Wakefit 4XL Bean Bag | 3 Month Warranty |",
    price: "2599.00",
    color: "Brown",
    badge: true,
    des: "Fade-resistant Premium Leatherette fabric with superior seam and tear strength for durability Cushion dimension :L 40.6 cm x W 30.4 cm (16 x 12 inches) | Footrest dimension 38.1 cm x 21.5 cm (15 x 8.5 inches) Care Instructions: Spot Clean with damp cloth DO NOT machine wash Convenient Handle & Double Stitched | 3 Months against manufacturing defects",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/41Q39rK5GrL._SX300_SY300_QL70_FMwebp_.jpg",
    productName: "GIGLICK 3XL Filled with Beans  Leather Bean Bag",
    price: "1999.00",
    color: "Red",
    badge: false,
    des: "Bean Bag Chair Sofa, Made of PVC Faux Leather, soft, practical and durable. We upgraded the fabric to a thicker, softer material that has stood the test of time. These comfortable bean bag chairs are definitely your favourite place to relax.✅【HAVE FUN】⭐ This bean bag chair is perfect for both indoor and outdoor use, different sizes for adults and kids, for outside relaxing as a fun to a sun chair, or as a bed chair for living room, bedroom, playroom, dorm room, etc.",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/31AmF2ThOiL.jpg",
    productName: "BLACK OAK Victor 2 Seater Sofa",
    price: "11999.00",
    color: "Black OAk",
    badge: false,
    des: "Product Dimension ( Length56 Inch) (Width19 Inch) (Heigh24 Inch). This Is A Regular Size Sofa Which Can Be Kept Easily In Your Living Room<br> Clothe Material;High Quality Fabric ,Colour; Beige, Frame Material; Sal Wood, Filling Material;32 Density Foam Product Will Be Shipped In A Pre Assembled State Directly At Your Doorstep. We Also Provide After Sales Service To All Our Customer. BLACK OAK Products Always Comes With 3 Years Warranty As Our Main Priority Is Quality And We Ourselve Manufacture These Products"
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/41hwu2nJfrL.jpg",
    productName: "BLACK OAK Sissel Upholstered Storage Bench Sofa",
    price: "8499.00",
    color: "BlUE",
    badge: true,
    des: "Product Dimension ( Length 52 inch) (Width 17 inches) (Height 19 inch). This Is A Regular Size Sofa Which Can Be Kept Easily In Your Living Room Colour; Blue , Frame Material; Sal Wood, Filling Material;32 Density Foam Product Will Be Shipped In A Pre Assembled State Directly At Your Doorstep. We Also Provide After Sales Service To All Our Customer. BLACK OAK Products Always Comes With 3 Years Warranty As Our Main Priority Is Quality And We Ourselve Manufacture These Products",
  },
];
// =================== Furniture data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/51UMj1QGe-L._SL1500_.jpg",
    productName: "Christian Dior Eau Sauvage Eau De Toilette Bottle",
    price: "16499",
    color: "Wood",
    badge: true,
    des: "Brand: Dior Item Form Spray Item Volume: 200 Millilitres Scent Wood  Special Feature: Travel Size",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/51vZwMd0pzL._SL1000_.jpg",
    productName: "Christian Dior Dior Homme Eau De Toilette Spray",
    price: "8249",
    color: "White",
    badge: false,
    des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 5 Fluid Ounces ,Scent: Christian Dior Dior Homme Eau De Toilette Spray ,Special Feature: Travel Size",
  },
  {
  _id: "202",
  img: "https://m.media-amazon.com/images/I/51IAhbeRCAL._SL1000_.jpg",
  productName: "Dior Homme by Christian Dior for Men 3.4 oz Eau de",
  price: "13752",
  color: "Golden",
  badge: false,
  des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 100 Millilitres ,Scent: Lavender, Musk , Fruity, Mint ,Special Feature: Travel Size",
},
{
  _id: "201",
  img: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
  productName: "Apple MacBook Air Laptop M2",
  price: "79999",
  color: "Black and White",
  badge: true,
  des: "13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of color ,System on Chip (SoC), Apple M1 chip, 8-core CPU with 4 performance cores and 4 efficiency cores, 16-core Neural Engine",
},
{
  _id: "202",
  img: "https://m.media-amazon.com/images/I/71bhWgQK-cL._SL1500_.jpg",
  productName: "Apple AirPods Pro MagSafe Charging Case",
  price: "16990.00",
  color: "White",
  badge: false,
  des: "Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking places sound all around you , Adaptive EQ automatically tunes music to your ears , Three sizes of soft, tapered silicone tips for a customisable fit",
},
{
  _id: "203",
  img: "https://m.media-amazon.com/images/I/81IfN-Rw8uL._SL1500_.jpg",
  productName: "New Apple AirPods Max - Silver",
  price: "59900.00",
  color: "Gray",
  badge: false,
  des: "Apple-designed dynamic driver provides high-fidelity audio , Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking provides theater-like sound that surrounds you , Computational audio combines custom acoustic design with the Apple H1 chip and software for breakthrough listening experiences , Designed with a knit-mesh canopy and memory foam ear cushions for an exceptional fit.",
},
{
  _id: "204",
  img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Ff1%2F97%2Ff1973e0dabdf30d1754178d9bcbd17e28b198f1e.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bkids_boys_clothing_trousersjeans_joggerssweatpants%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
  productName: "Brushed-inside joggers",
  price: "999",
  color: "Light grey marl",
  badge: true,
  des: "Joggers in sweatshirt fabric made from a cotton blend with a soft brushed inside. Covered elastication and a drawstring at the waist, side pockets and ribbed hems.",
},
{
  _id: "205",
  img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F61%2Fd5%2F61d5c650f58c8d2ad6801ef124bacbe7f3c38364.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
  productName: "2-piece sweatshirt set",
  price: "1499",
  color: "Green/Brooklyn",
  badge: true,
  des: "Cosy set in lightweight sweatshirt fabric. Long-sleeved top with a round neckline and dropped shoulders. Ribbing around the neckline, cuffs and hem. Bottoms with an elasticated, drawstring waist and ribbed hems.",
},
{
  _id: "206",
  img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F14%2Fb8%2F14b8e7c9d6e526620b07e42ba609d36bf0392161.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bkids_boys_clothing_trousersjeans_joggerssweatpants%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
  productName: "3-pack joggers",
  price: "2199",
  color: "Navy blue/Light grey marl",
  badge: true,
  des: "Joggers in soft cotton jersey with an elasticated waist, pockets in the side seams and ribbed hems.",
},
{
  _id: "207",
  img: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-x510nliainu/gallery/in-galaxy-tab-s9-fe-sm-x510-sm-x510nliainu-thumb-538493081?imwidth=480",
  productName: "Galaxy Tab S9 FE",
  price: "36999",
  color: "Pink",
  badge: true,
  des: "Color and model availability may vary depending on country or carrier  The display used in Galaxy Tab S9 FE and Tab S9 FE+ has received the Low Blue Light certification from SGS based on its ability to reduce some of the blue light emission from the screen. More information of this certification can be found on www.sgs.com/performance  Blue light certification target is under 9.9% (test from SGS)  Typical value tested under third-party laboratory conditions. Typical value is the estimated average value considering the deviation in battery capacity among the battery samples tested under IEC 61960 standard. Rated (minimum) capacity is 8,000 mAh for Galaxy Tab S9 FE and 10,090 mAh for Galaxy Tab S9 FE+. Actual battery life may vary depending on network environment, usage patterns and other factors  15W Fast Charging is supported when the Galaxy Tab S9 FE and Tab S9 FE+'s display is turned off and the battery level is at least 30%",
},
{
  _id: "208",
  img: "https://images.samsung.com/is/image/samsung/p6pim/in/ww80t504dab-tl/gallery/in-front-loading-washer-ww10t534daws1-374541-ww80t504dab-tl-383418964?$1300_1038_PNG$",
  productName: "8.0 kg Ecobubble™ Front Load Washing Machine ",
  price: "42000",
  color: "Black",
  badge: false,
  des: "Enjoy efficient cleaning, even at low temperatures* with Eco Bubble™ technology. Detergent is turned into bubbles, so it quickly penetrates fabric and removes dirt easily, while saving energy and protecting its color and texture**.",
},
{
  _id: "209",
  img: "https://images.samsung.com/is/image/samsung/p6pim/in/wa10bg4686brtl/gallery/in-wa4000b-435227-wa10bg4686brtl-533661234?$1300_1038_PNG$",
  productName: "9.0 kg Ecobubble™ Upper Load Washing Machine",
  price: "29300",
  color: "Gray",
  badge: false,
  des: "Give your laundry an intensive and hygienic cleaning with hot water and steam. The Hygiene Steam wash cycle washes clothes at 60°C to eliminate 99.9% of bacteria** and remove stubborn and oily stains***.",
},
{
  _id: "210",
  img: "https://m.media-amazon.com/images/I/61vN1isnThL._SX679_.jpg",
  productName: "Samsung Galaxy S20 FE 5G",
  price: "29999",
  color: "Dark Blue",
  badge: false,
  des: "5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM ,Triple Rear Camera Setup - 12MP (Dual Pixel) OIS F1.8 Wide Rear Camera + 8MP OIS Tele Camera + 12MP Ultra Wide | 30X Space Zoom, Single Take & Night Mode | 32MP F2.2 Front Punch Hole Camera",
},
{
  _id: "211",
  img: "https://m.media-amazon.com/images/I/41op1vdp-UL._SX300_SY300_QL70_FMwebp_.jpg",
  productName: "Samsung Galaxy M13",
  price: "9199",
  color: "Light Green",
  badge: false,
  des: "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase ,Upto 12GB RAM with RAM Plus | 64GB internal memory expandable up to 1TB| Dual Sim (Nano)",
},
{
  _id: "212",
  img: "https://m.media-amazon.com/images/I/61kAlJyn7QL._SX679_.jpg",
  productName: "Samsung Galaxy A34 5G",
  price: "27999",
  color: "Black",
  badge: false,
  des: "48MP(OIS)+8MP+5MP Triple camera setup - 48MP (F1.8) Main Camera with OIS + 8MP (F2.2) Ultra wide camera + 5MP (F2.4) depth camera | 13MP (F2.2) front camera 16.65 centimeters (6.6-inch) FHD+ Super AMOLED display, FHD+ resolution with 1080 x 2340 pixels , 393 PPI with 16M colours Android 13, v13.0 operating system with MediaTek | MTK D1080 2.6GHz,2GHz Octa-Core processor",
},
  {
    _id: 1016,
    img: "https://rukminim2.flixcart.com/image/416/416/kxxl9jk0/bar/n/u/h/high-density-pvc-pp-push-up-bar-stand-for-home-exercise-dips-original-imaga9rrdx6rb79n.jpeg?q=70",
    productName: "PRO365 High-density PVC & PP Stand For Home Exercise ",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "1) Tilt design : We Used Tilt Design In Our Push Up Bar For Men And Women Which Will Reduce Pressure From Your Wrist So You Can Do More Counts Of Push Ups At One Time. With This Single Equipment You Can Exercise Multiple Parts Of Your Body E.g. Chest, Back, Shoulder, Biceps Workout. 2) Easy to assemble : Our Push Up Bar Is So Easy To Assemble That Kids Can Also Easily Assemble .",
  },
  {
    _id: 1017,
    img: "https://rukminim2.flixcart.com/image/416/416/kzogn0w0/computer/j/u/m/14a-ca0504tu-thin-and-light-laptop-hp-original-imagbmt6dsjhwwhz.jpeg?q=70",
    productName: "HP 360 Intel Celeron Quad Core N4020 Chromebook  (14 Inch, Forest Teal, 1.49) ",
    price: "16990.00",
    color: "silver",
    badge: false,
    des: "--It is convertible with touch screen-- lightweight and easy to carry-- performance wise it was good to watch videos and check emails.-- battery backup was very good it usually comes around 4 hours.",
  },
  {
    _id: 1018,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/bedding-set/j/c/a/prime-home-collection-cotton-king-size-quilt-set-double-king-original-imagnreywf9z8kun.jpeg?q=70",
    productName: "BSB HOME Cotton Double King Sized Bedding Set  ",
    price: "440.00",
    color: "Black",
    badge: true,
    des: "BSB HOME Presents 4pc Comforter Set:- 1 Bedsheet 90*90 inches with 2 large size Pillow Covers 17x27 inches. 1 reversible comforter Material:- Microfiber",
  },
  {
    _id: 1019,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/car-cover/l/n/m/no-metallic-silver-triple-coated-inner-soft-lining-cotton-original-imagjf9xmyzjdrup.jpeg?q=70",
    productName: "GARREGE Car Cover For Maruti Baleno ",
    price: "1217.00",
    color: "white",
    badge: false,
    des: "Description:-Only Garrrege Waterproof Baleno Car Cover Brings indian monsoon capability car body cover which is made from 130gsm foam coated of inner side and exterior is 30 gsm waterproof pvc material ,we sold too many fabrics during 2010 but when we got inner foam fabric which is produce good protection in india and sacrifice indian every monsoon very easily and be strong always not fading easily not torn easily ,this Grey cover 130gsm",
  },
  {
    _id: 1020,
    img: "https://m.media-amazon.com/images/I/717kxMoZiAL._UY679_.jpg",
    productName: "Lymio Casual Shirt for Men Shirt for Men||",
    price: "399.00",
    color: "Mixed",
    badge: false,
    des: "Care Instructions: Dry Clean OnlyFit Type: Regular Fitshirt for men || casual shirt for men || men stylish shirt || men Printed Shirthalf Sleeve",
  },
  {
    _id: 1021,
    img: "https://m.media-amazon.com/images/I/81buwNeKIFL._UY679_.jpg",
    productName: "Laxeric Casual Shirt for Men|| Shirt for Men||",
    price: "399.00",
    color: "Mixed",
    badge: true,
    des: "Style - Enhance your look by wearing this Casual Stylish Men's shirt, Team it with a pair of tapered denims Or Solid Chinos and Loafers for a fun Smart Casual look",
  },
  {
    _id: 1022,
    img: "https://m.media-amazon.com/images/I/51n9O8VDj3L._SX300_SY300_QL70_FMwebp_.jpg",
    productName: "ELLVELLON Pack of 2 Shelves Multipurpose, ",
    price: "290.00",
    color: "Black",
    badge: true,
    des: "✔️ [ Hassle Free Shelve ]: no nails, no drilling, 2 traceless locking stickers for mounting on wall, This bathroom fittings accessories set shelves, kitchen corner shelf, bathroom cabinets for storage can bear things up to 5 kg.",
  },
  {
    _id: 1023,
    img: "https://m.media-amazon.com/images/I/41YjSD1XPoS._SY300_SX300_QL70_FMwebp_.jpg",
    productName: "Callas Multipurpose Foldable Laptop Table with Cup Holder Drawer | Mac Holder | Study Table, Breakfast Table, Foldable ",
    price: "635.00",
    color: "Blank and White",
    badge: false,
    des: "【LARGE SIZE】 - 23.42(L) x 15.55(W) x 8.97(H) Inch. Callas Lap Desk perfectly fits nearly all size laptop,or tablet & phone, also can put a mouse and books. There is ample space to work, study, eat breakfast or dessert on the bed table. Package Contain : 1 Laptop Table.",
  },
  {
    _id: 1024,
    img: "https://m.media-amazon.com/images/I/41EM0Pa5jAL._SX300_SY300_QL70_FMwebp_.jpg",
    productName: "Amazon Basics Digital safe with electronic keypad",
    price: "7535.00",
    color: "Blank and White",
    badge: false,
    des: "Please refer the product manual before installation & first setup. Kindly ensure to keep the back-up key in a safe place for future use. In case of issues during fingerprint or pin set-up, kindly use new batteries1.8 cubic feet home safe for storing important documents, jewelry, and other valuables. Programmable electronic keypad ensures secure, easy operation; back-up key for emergency use",
  },
  {
    _id: 1025,
    img: "https://m.media-amazon.com/images/I/21R-Jz7Qb7L._SY445_SX342_QL70_FMwebp_.jpg",
    productName: "Whirlpool 190 L 3 Star Direct-Cool Single",
    price: "13840.00",
    color: "Gray",
    badge: true,
    des: "The star rating changes are as per BEE guidelines on or before 1st Jan 2023 Direct-cool refrigerator: 190 L with 3S Energy rating Faster cooling & Better cooling efficiency with Insulated capillary technology",
  },
  {
    _id: 1026,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/refrigerator-new/p/n/6/-original-imagn2z8fzmhrcfz.jpeg?q=70",
    productName: "LG 185 L Direct Cool Single Door",
    price: "15390.00",
    color: "gray",
    badge: false,
    des: "You can free up some of your kitchen space by storing vegetables like onions and potatoes at room temperature inside your fridge, thanks to the LG Direct Cool Single-door Refrigerator. Sporting the Smart Connect technology, it can draw power from your home inverter during power cuts to prevent your food from going bad. Additionally, owing to its ability to run on sunlight, this is a solar-smart refrigerator. Furthermore, it is also capable of delivering ice within a short duration.",
  },
  {
    _id: 1027,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/refrigerator-new/l/g/1/-original-imagm8xezmbenjsw.jpeg?q=70",
    productName: "SAMSUNG 183 L Direct Cool Single Door 2 Star ",
    price: "14890.00",
    color: "dark blue",
    badge: false,
    des: "High-performance and practical, the Samsung Refrigerator is an exceptional addition to your kitchen. It offers energy efficiency, minimal operating noise, and long-lasting durability with its Digital Inverter technology. And, the Digital Inverter Compressor in this refrigerator automatically changes its speed in response to cooling needs. Also, this refrigerator is protected from voltage fluctuations because it operates with a wide voltage range of 100 V to up to 300 V. Moreover, without requiring a stabiliser, it can keep running steadily and smoothly.",
  },
  {
    _id: 1028,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/ceiling-lamp/y/u/j/6-1-60-60-5-7-adw-600mm-black-gold-adwait-original-imags59gragmphda.jpeg?q=70",
    productName: "Adwait crystal Black glod polish metal 600mm chandelier hanging",
    price: "7489.00",
    color: "gold and White",
    badge: false,
    des: "The lampshade consists of many shining Polygon crystal,the effect of crystal refraction create a comfortable and elegant ambiance. decorative modern indoor Chandilers for hotel or villa. DURABLE AND SPACE SAVING - Shatter-Resistant Luxury Crystal and stainless steel will not rust or be damaged. ENERGY SAVING - led light , energy saving, durable, stable and safe, bring you into a healthy lighting experience.Max support 5W Led. GREAT FOR INDOOR OR HOME LIGHTING - The simple and modern design can be more fashionable, make your house look bright, tidy and spacious, add a lot of elegance.",
  },
  {
    _id: 1029,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/ceiling-lamp/z/q/7/3-35-35-5-crystal-glass-chandelier-for-living-room-modern-3lww-original-imagmquhjsghvak6.jpeg?q=70",
    productName: "honeywolf 3LyRound Warmwhite Crystal Chandelier for Living Room,",
    price: "6100.00",
    color: "Gold",
    badge: true,
    des: "The lampshade consists of many shining Polygon lamps,the effect of led`s refraction create a comfortable and elegant ambiance. decorative modern indoor Chandilers for hotel or villa. DURABLE AND SPACE SAVING - Shatter-Resistant Luxury Crystal and stainless steel will not rust or be damaged. ENERGY SAVING - led light , energy saving, durable, stable and safe, bring you into a healthy lighting experience.Max support 5W Led. GREAT FOR INDOOR OR HOME LIGHTING - The simple and modern design can be more fashionable, make your house look bright.",
  },
  {
    _id: 1030,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/wall-lamp/x/l/q/11-light-bird-gold-hanging-blissballs-blissbells-1-14-original-imagqbr2dmh84jxs.jpeg?q=70",
    productName: "Blissbells Wallchiere Wall Lamp With Bulb",
    price: "4,619.00",
    color: "Gold, WARN WHITE",
    badge: true,
    des: "Led Modern Style Crystal Short Shaded Pendant Chandelier Material: Metal, Crystal; Fixture finish: Gold; Crystal: clear Fixture: Included Inbuilt Led Light No Bulb Needed",
  },
  {
    _id: 1031,
    img: "https://rukminim2.flixcart.com/image/832/832/krf91u80/precious-pendant-locket/6/o/x/na-fjs-1102-femme-jam-original-imag57sycyg6w5xy.jpeg?q=70",
    productName: "Femme JamSterling Silver",
    price: "1759.00",
    color: "Black",
    badge: false,
    des: "This product doesn't require installation , Femme Jam Platinum 925 Sterling Silver, Natural Blue Topaz Gemstone Pendant Set | Topaz Earring & Pendant Set    ",
  },
  {
    _id: 1032,
    img: "https://rukminim2.flixcart.com/image/832/832/l0mr7gw0/precious-earring/u/g/3/na-3-16-gtin009a-jhumki-earring-lords-jewels-original-imagcdgvngfrdjbp.jpeg?q=70",
    productName: " Classical Yellow Gold 22kt Jhumki Earring",
    price: "22968.00",
    color: "Gold",
    badge: true,
    des: " COD orders upto Rs.49,999 are only allowed for all precious jewellery and coins. 22kt Jhumki - COD orders upto Rs.49,999 are only allowed for all precious jewellery and coins. Brand LORDS JEWELS Model Number GTIN009A Model Name Maha Laxmi Ji Classical",
  },
  {
    _id: 1033,
    img: "https://rukminim2.flixcart.com/image/832/832/ksoz53k0/precious-nose-ring-stud/2/p/h/si-dnp035-lords-jewels-original-imag67amwvbgkf3h.jpeg?q=70",
    productName: "Swastik Diamond Nose Pin 18kt  Yellow Gold ",
    price: "5490.00",
    color: "Gold",
    badge: true,
    des: "Diamond Nose Pin, Diamond Authenticity Certificate - As per the government guidelines on KYC, in a day the customer is only allowed to buy precious jewellery and coins worth a maximum of Rs. 1,99,999 for PREPAID orders. Brand LORDS JEWELS Model Number DNP035 Model Name Swastik Diamond Nose Pin Type Stud Ideal For Women, Girls Occasion Everyday",
  },
  {
    _id: 1034,
    img: "https://rukminim2.flixcart.com/image/416/416/jwmfcsw0/book/4/1/9/bd-chaurasia-s-handbook-of-general-anatomy-6-e-paperback-2019-original-imafh7bkhdzcmuwz.jpeg?q=70",
    productName: "BD Chaurasia's Handbook of General Anatomy",
    price: "249.00",
    color: "white",
    badge: false,
    des: "  Language: English  Binding: Paperback  Publisher: CBS Publishers & Distributors  Genre: Medical  ISBN: 9788194125419, 9788194125419  Edition: 6th  Pages: 384",
  },
  {
    _id: 1035,
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/t/i/d/energize-your-mind-original-imagrtzwf6qczgyz.jpeg?q=70",
    productName: "Energize your mind by Gaur Gopal Das ",
    price: "289.00",
    color: "White",
    badge: false,
    des: "Take charge of your mind. Be in charge of your life. In this book, bestselling author and life coach Gaur Gopal Das decodes how the mind works. He combines his anecdotal style with analytical research to teach us how to discipline our mind for our greater well-being. Throughout this book, he provides interactive exercises, meditation techniques and worksheets to help us take charge of our mind. This book is an essential read for anyone who wants to work towards a better, more fulfilling future for themselves.",
  },
  {
    _id: "236",
    img: "https://m.media-amazon.com/images/I/61YdD9veZXL._SL1500_.jpg",
    productName: "Turtle® Dual Layer Hard Case for Apple iPhone 14 Back Cover ",
    price: "999.00",
    color: "Aqua",
    badge: false,
    des: " TURTLE Case Outside Hard PC + Inside Soft TPU are Provided with Perfect Quality Finish & Precious Cut-Outs for all Ports & Camera. Easy Access of Buttons, Camera, Audio Jack & Charging Ports.TURTLE Case Inside Soft TPU Can Cover The Edges Of Both Side, Covers All Corners, Keep The Phone From Scratching Or Touching The Ground, Durable & Shockproof.",
  },
  {
    _id: "237",
    img: "https://m.media-amazon.com/images/I/515SgB2O-2L._SL1500_.jpg",
    productName: "SQUIF Airtag Case for Apple Airtags Silicone Case Protective Cover ",
    price: "249.00",
    color: "Black",
    badge: false,
    des: "Exclusively Compatible with AirTag (2021) Only. AirTag Device is not included ,Easy to Use with Hook Ring Option, Multi-Purpose, Stylish, Washable, Durable ,Convenient Keychain: With a durable keychain ring, you can easily attach the Airtag Finder to your important items. Bags for kids, keychains for parents, dog leashes, car keys, and more. There's no need to be concerned about losing your location",
  },
  {
    _id: "238",
    img: "https://m.media-amazon.com/images/I/61XCCsBoDgL._SL1500_.jpg",
    productName: "Apple iPhone 14 Pro Max Clear Case with MagSafe ​​​​​​​Protective",
    price: "4990.00",
    color: " Clear",
    badge: true,
    des: " Crafted with a blend of optically clear polycarbonate and flexible materials, the case fits right over the buttons for easy use. On the surface, a scratch-resistant coating has been applied to both the interior and exterior. And all materials and coatings are optimised to prevent yellowing over time.With built-in magnets that align perfectly with iPhone 14 Pro Max, this case offers a magical attach experience and faster wireless charging",
  },
  {
    _id: "239",
    img: "https://m.media-amazon.com/images/I/711NysppfvL._SL1500_.jpg",
    productName: "Christian Dior Women's Miss Dior Blooming Bouquet EDT Spray (New Scent)",
    price: "10049",
    color: "Pink",
    badge: false,
    des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 100 Millilitres ,Scent: Dior Miss Dior Blooming ,Special Feature: Travel Size",
  },
  {
    _id: "240",
    img: "https://m.media-amazon.com/images/I/617cIMD0onL._SL1500_.jpg",
    productName: "Dior Poison for Women, 100ml Amber honey berries and spice.",
    price: "17085",
    color: "Black",
    badge: true,
    des: " Poison by Christian Dior EDT spray 100.55ml Design house: Christian Dior Year introduced: 1985 Recommended use: Romantic Brand: Dior ,Item Form: Spray ,Item Volume: 3.4 Fluid Ounces ,Scent: Fresh ,Special Feature: Travel Size",
  },
  {
    _id: "241",
    img: "https://m.media-amazon.com/images/I/41JwXH1M+tL._SL1000_.jpg",
    productName: "Dior Addict by Christian Dior Eau Fraiche Spray 1.7 oz for Women",
    price: "15470",
    color: "White",
    badge: false,
    des: "Eau Fraiche Spray ,Authenic ,Fragrance ,Quality Dior Addict indulges the senses with sumptuous silk tree flower, voluptuous night queen flower, and luscious bourbon vanilla combined with sandalwood and tonka bean to evoke a feeling of passion in the woman who wears it. Sensual. Soft.",
  },
  {
    _id: "242",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1463003120/433148_CPWE0_9075_001_100_0000_Light-Childrens-Ace-leather-sneaker.jpg",
    productName: "CHILDREN'S ACE LEATHER SNEAKER",
    price: "36640",
    color: "White",
    badge: true,
    des: "Presented here with a green leather trim and the House Web in green and red, a reinterpretation of the Ace sneaker that imbues the everlasting qualities of style",
  },
  {
    _id: "243",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1658073610/681374_U4G20_4464_002_100_0000_Light-Childrens-Double-G-ballet-flat.jpg",
    productName: "CHILDREN'S DOUBLE G BALLET FLAT",
    price: "45820",
    color: "White and Black",
    badge: true,
    des: "The House logo continues to enrich collections in contemporary new ways. Here, the Double G appears as part of a geometric cotton motif atop this children's ballet flat.",
  },
  {
    _id: "244",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1682704849/750709_FAB5S_6452_002_100_0000_Light-Childrens-Gucci-Tennis-1977-high-top-sneaker.jpg",
    productName: "CHILDREN'S GUCCI TENNIS 1977 HIGH-TOP SNEAKER",
    price: "50799",
    color: "Pink and White",
    badge: true,
    des: "OshKosh B'gosh made its name by designing hickory-striped denim bib overalls in mini dimensions for children. From casual playwear to special occasions, here signature Gucci pieces are emblazoned with the two logos and enriched with playful patches and prints bearing four-leaf clovers and cuddly bears.",
  },
  {
    _id: "245",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1690994820/760228_96IWT_8745_001_079_0000_Light-GG-duffle-bag.jpg",
    productName: "GG DUFFLE BAG ",
    price: "320134",
    color: "Brown leather trim",
    badge: true,
    des: "The Web stripe has remained one of the most symbolic codes of the House since its introduction. The distinguishing emblem appears in green and red atop this duffle bag. Completing the design's logo feel, the style is crafted from the unmistakable GG Supreme canvas.",
  },
  {
    _id: "246",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1584034204/625549_96IWG_8745_001_100_0000_Light-Ophidia-pouch.jpg",
    productName: "OPHIDIA POUCH",
    price: "74420",
    color: "Green and Red ",
    badge: true,
    des: "The zippered pouch is introduced within the Ophidia collection in GG Supreme canvas with brown leather trim. First used in the 1970s, the GG logo was an evolution of the original Gucci rhombi design from the 1930s, and from then it's been an established symbol of Gucci's heritage. The pouch combines the signature motif with the Web stripe—a timeless pairing that pays homage to Gucci's roots.",
  },
  {
    _id: "247",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1658161841/360_693664_96IWT_8745_001_100_0000_Light-Gucci-Savoy-medium-trolley.jpg",
    productName: "GUCCI SAVOY MEDIUM TROLLEY",
    price: "315374",
    color: "Mixed",
    badge: false,
    des: "n archival design from the 1930s inspired the GG Supreme canvas, now one of the House's most emblematic materials. Traditionally presented in beige and ebony, it is an ode to timeless pieces and everlasting design. An brown leather trim completes this medium Gucci Savoy wheel suitcase, while the green and red Web detail adds a subtle reference to the House archives.",
  },
];
// =================== PaginationItems End here =================

// =================== Electronics data Start here ============
export const Electronics = [
  {
    _id: "207",
    img: "https://m.media-amazon.com/images/I/81tusZvwFGL._SX679_.jpg",
    productName: "Samsung Galaxy M34 5G",
    price: "18499",
    color: "Silver",
    badge: false,
    des: "16.42 Centimeters (6.5-Inch) Super AMOLED Display, FHD+ Resolution, 1080 x 2340 Pixels Protected by Corning Gorilla Glass 5 ,50MP+8MP+2MP Triple Camera Setup - True 50MP No Shake Cam (F1.8) Main Camera + 8MP (F2.2) + 2MP (F2.4)| 13MP (F2.0) Front Camera",
  },
  {
    _id: "208",
    img: "https://m.media-amazon.com/images/I/8155EFAxDzL._SX679_.jpg",
    productName: "Samsung Galaxy M14 5G",
    price: "11990",
    color: "Green",
    badge: false,
    des: "Superfast 5G with 13 5G Bands, Powerful Exynos 1330 Octa Core 2.4GH 5nm processor with latest Android 13 having One UI 5.0 interface ,50MP+2MP+2MP Triple camera setup- True 50MP (F1.8) main camera + 2MP (F2.4) + 2MP (F2.4)| 13MP (F2.0) front camera",
  },
  {
    _id: "209",
    img: "https://m.media-amazon.com/images/I/41kg-+XWoxL._SY300_SX300_.jpg",
    productName: "Samsung Galaxy M04 Blue",
    price: "6499",
    color: "Dark Blue",
    badge: false,
    des: "Powerful MediaTek Helio P35 Octa Core 2.3GHz with Android 12,One UI Core 4.1 13MP+2MP Dual camera setup- True 13MP (F2.2) main camera + 2MP (F2.4) | 5MP (F2.2) front came 16.55 centimeters (6.5-inch) LCD, HD+ resolution with 720 x 1600 pixels resolution, 269 PPI with 16M color",
  },
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    productName: "Apple MacBook Air Laptop M2",
    price: "79999",
    color: "Black and White",
    badge: true,
    des: "13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of color ,System on Chip (SoC), Apple M1 chip, 8-core CPU with 4 performance cores and 4 efficiency cores, 16-core Neural Engine",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/71bhWgQK-cL._SL1500_.jpg",
    productName: "Apple AirPods Pro MagSafe Charging Case",
    price: "16990.00",
    color: "White",
    badge: false,
    des: "Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking places sound all around you , Adaptive EQ automatically tunes music to your ears , Three sizes of soft, tapered silicone tips for a customisable fit",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/81IfN-Rw8uL._SL1500_.jpg",
    productName: "New Apple AirPods Max - Silver",
    price: "59900.00",
    color: "Gray",
    badge: false,
    des: "Apple-designed dynamic driver provides high-fidelity audio , Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking provides theater-like sound that surrounds you , Computational audio combines custom acoustic design with the Apple H1 chip and software for breakthrough listening experiences , Designed with a knit-mesh canopy and memory foam ear cushions for an exceptional fit.",
  },
  {
    _id: "210",
    img: "https://m.media-amazon.com/images/I/61vN1isnThL._SX679_.jpg",
    productName: "Samsung Galaxy S20 FE 5G",
    price: "29999",
    color: "Dark Blue",
    badge: false,
    des: "5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM ,Triple Rear Camera Setup - 12MP (Dual Pixel) OIS F1.8 Wide Rear Camera + 8MP OIS Tele Camera + 12MP Ultra Wide | 30X Space Zoom, Single Take & Night Mode | 32MP F2.2 Front Punch Hole Camera",
  },
  {
    _id: "211",
    img: "https://m.media-amazon.com/images/I/41op1vdp-UL._SX300_SY300_QL70_FMwebp_.jpg",
    productName: "Samsung Galaxy M13",
    price: "9199",
    color: "Light Green",
    badge: false,
    des: "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase ,Upto 12GB RAM with RAM Plus | 64GB internal memory expandable up to 1TB| Dual Sim (Nano)",
  },
  {
    _id: "212",
    img: "https://m.media-amazon.com/images/I/61kAlJyn7QL._SX679_.jpg",
    productName: "Samsung Galaxy A34 5G",
    price: "27999",
    color: "Black",
    badge: false,
    des: "48MP(OIS)+8MP+5MP Triple camera setup - 48MP (F1.8) Main Camera with OIS + 8MP (F2.2) Ultra wide camera + 5MP (F2.4) depth camera | 13MP (F2.2) front camera 16.65 centimeters (6.6-inch) FHD+ Super AMOLED display, FHD+ resolution with 1080 x 2340 pixels , 393 PPI with 16M colours Android 13, v13.0 operating system with MediaTek | MTK D1080 2.6GHz,2GHz Octa-Core processor",
  },
  {
    _id: "213",
    img: "https://m.media-amazon.com/images/I/71UCpBBIfaL._SX679_.jpg",
    productName: "Samsung Galaxy Watch4 Bluetooth",
    price: "11990",
    color: "Black",
    badge: false,
    des: "Only compatible with Android Smartphones (Runs on Wear OS Powered by Samsung) Bioelectrical Impedance Analysis Sensor for Body Composition Analysis, Optical Heart Rate Sensor.Health Monitoring features such as Advanced Sleep Analysis & Women's Health.",
  },
  {
    _id: "214",
    img: "https://m.media-amazon.com/images/I/61mkpp+F95L._SX522_.jpg",
    productName: "Samsung Galaxy Watch4 Classic LTE (4.6cm, Black)",
    price: "17799",
    color: "White",
    badge: false,
    des: "nly compatible with Android Smartphones (Runs on Wear OS Powered by Samsung) Bioelectrical Impedance Analysis Sensor for Body Composition Analysis, Optical Heart Rate Sensor. Health Monitoring features such as Advanced Sleep Analysis & Women's Health. Enhanced Fitness tracking lets you track 90+ workouts; Enriched App availability and connectivity with Wear OS, Powered by Samsung Included Components: ‎Galaxy Watch::Watch Strap::Wireless Charger::Quick Start Quide; Connectivity Technology: Usb; Item Type Name: Smart Watch",
  },
  {
    _id: "215",
    img: "https://m.media-amazon.com/images/I/61XmNBJTyNL._SX679_.jpg",
    productName: "Samsung Galaxy Watch5 Bluetooth ",
    price: "19999",
    color: "Purple",
    badge: false,
    des: "Sleep Tracking: Know your sleep with our new and improved sleep tracking technology. Plan your bedtime, detect snoring, understand and track your sleep. ,Body composition Analysis (BIA Measurement): Monitor everything from body fat percentage (BIA) to skeletal muscle weight. All the feedback you need to track your progress.",
  },
  
];
// =================== Electronics data End here ==============
// =================== clothes data Start here ============
export const Clothes = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/712r6exQc+L._UL1500_.jpg",
    productName: "SGF11 Women's Kanjivaram Soft Silk Saree",
    price: "949",
    color: "Blank and White",
    badge: false,
    des: "Fabric: Kanchipuram Silk, Blouse Fabric Kanchipuram Silk. Work: Jacquard Woven Stylish Sari, Stylish Woven.",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/81buwNeKIFL._UY679_.jpg",
    productName: "Laxeric Casual Shirt for Men|| Shirt for Men||",
    price: "399.00",
    color: "Mixed",
    badge: true,
    des: "Style - Enhance your look by wearing this Casual Stylish Men's shirt, Team it with a pair of tapered denims Or Solid Chinos and Loafers for a fun Smart Casual look",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/717kxMoZiAL._UY679_.jpg",
    productName: "Lymio Casual Shirt for Men Shirt for Men||",
    price: "399.00",
    color: "Mixed",
    badge: false,
    des: "Care Instructions: Dry Clean OnlyFit Type: Regular Fitshirt for men || casual shirt for men || men stylish shirt || men Printed Shirthalf Sleeve",
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/61-QfaonpML._UL1440_.jpg",
    productName: "Pratham Blue Women's Silk Saree",
    price: "650.00",
    color: "Blue",
    badge: true,
    des: "Hand Wash Only Saree Color- Blue, Saree Material- Silk, Saree Length- 6.3 Blouse Details: Blouse Color-Blue, Blouse Material- Satin, Blouse Length- 0.8 m, Blouse Work Type- Sequins Embroidered Work ,Border & Pallu Details: Border Color- Blue, Pallu Color- Blue",
  },
];
// =================== clothes data End here ==============
// =================== Bags data Start here ============
export const Bags = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/61odaW2PSyL._UL1280_.jpg",
    productName: "Safari Seek 45 Ltrs Overnighter Expandable",
    price: "2149.00",
    color: "Black",
    badge: false,
    des: "Care Instructions: Hand Wash Only ,Laptop Compatibility: Yes, Laptop Size: 17 inches,Outer Material: Polyester, Color: Black,Weight: 1.20 grams; Dimensions: 53 cms x 32 cms x 27 cms (LxWxH) ,Number of compartments: 1; Warranty type: Manufacturer; 18 months ,Closure Type: Zipper; Special Features: Back Padding; Pocket Description: Utility Pocket; Age Range Description: Adult",
  },
  {
    _id: "202",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/backpack/s/r/h/-original-imagtehgzjuccvcw.jpeg?q=70",
    productName: "Large 35 L Backpack Clan   Polyester Men & Women(Blue)",
    price: "939.00",
    color: "Sky",
    badge: false,
    des: "At Safari, we have endeavored to provide the best service to our consumersSafari is committed to providing the best in class product to its consumer. We take the utmost care to ensure ",
  },
  {
    _id: "203",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/backpack/q/q/3/-original-imaghzzuxhezyhm8.jpeg?q=70",
    productName: "Medium 30 L Laptop Backpack ASHPER CB  (Blue)",
    price: "779.00",
    color: "Black",
    badge: true,
    des: "Safari is committed to providing the best in class product to its consumer. We take the utmost care to ensure that our products are of the highest standard. At Safari, we have endeavored to provide the best service to our consumers",
  },
  {
    _id: "204",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/backpack/b/e/s/-original-imaghassmgqg8fvk.jpeg?q=70",
    productName: "Medium 29 L Laptop Backpack SPIN LAPTOP BACKPACK 01 - TEAL  (Blue)",
    price: "1099.00",
    color: "Blue",
    badge: false,
    des: "Damage caused by misuse (such as transportation of unusual items), neglect, accidents, abrasion, exposure to extreme temperatures, solvents, acids, water, normal wear and tear or transport damage (by airlines for example).",
  },
];
// =================== Bags data End here ==============
// =================== appliance data Start here ============
export const Appliance = [
  {
    _id: "201",
    img: "",
    productName: "Samsung Galaxy S23 5G",
    price: "79999",
    color: "Green and White",
    badge: true,
    des: "Nightography's enhanced AI keeps details clear, so low light photos and videos will be bright and colorful from dusk to dawn and back again.",
  },
  {
    _id: "202",
    img: "https://rukminim2.flixcart.com/image/416/416/k3q76a80/camera/x/u/e/sony-apsc-ilce-6100y-b-in5-mirrorless-original-imafm6msr4fghzfw.jpeg?q=70",
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: "spfThree",
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: "https://rukminim2.flixcart.com/image/416/416/k3q76a80/camera/x/u/e/sony-apsc-ilce-6100y-b-in5-mirrorless-original-imafm6msr4fghzfw.jpeg?q=70",
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Appliance data End here ==============
// =================== Gucci data Start here ============
export const Gucci = [
  {
    _id: "201",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1690994820/760228_96IWT_8745_001_079_0000_Light-GG-duffle-bag.jpg",
    productName: "GG DUFFLE BAG ",
    price: "320134",
    color: "Brown leather trim",
    badge: true,
    des: "The Web stripe has remained one of the most symbolic codes of the House since its introduction. The distinguishing emblem appears in green and red atop this duffle bag. Completing the design's logo feel, the style is crafted from the unmistakable GG Supreme canvas.",
  },
  {
    _id: "202",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1584034204/625549_96IWG_8745_001_100_0000_Light-Ophidia-pouch.jpg",
    productName: "OPHIDIA POUCH",
    price: "74420",
    color: "Green and Red ",
    badge: true,
    des: "The zippered pouch is introduced within the Ophidia collection in GG Supreme canvas with brown leather trim. First used in the 1970s, the GG logo was an evolution of the original Gucci rhombi design from the 1930s, and from then it's been an established symbol of Gucci's heritage. The pouch combines the signature motif with the Web stripe—a timeless pairing that pays homage to Gucci's roots.",
  },
  {
    _id: "203",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1658161841/360_693664_96IWT_8745_001_100_0000_Light-Gucci-Savoy-medium-trolley.jpg",
    productName: "GUCCI SAVOY MEDIUM TROLLEY",
    price: "315374",
    color: "Mixed",
    badge: false,
    des: "n archival design from the 1930s inspired the GG Supreme canvas, now one of the House's most emblematic materials. Traditionally presented in beige and ebony, it is an ode to timeless pieces and everlasting design. An brown leather trim completes this medium Gucci Savoy wheel suitcase, while the green and red Web detail adds a subtle reference to the House archives.",
  },
  {
    _id: "204",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1668707154/360_743718_9AACE_8188_001_100_0000_Light-Gucci-Porter-cabin-plus-trolley-with-strap.jpg",
    productName: "GUCCI PORTER CABIN PLUS TROLLEY WITH STRAP",
    price: "316174",
    color: "Silver  ",
    badge: true,
    des: "Referencing the House's beginnings in the world of luggage and Guccio Gucci’s time at the Savoy Hotel in London, travel items continue to evolve to embrace the contemporary. This cabin trolley is presented in silver aluminum, complete with a green and red Web luggage strap to secure the suitcase",
  },
  {
    _id: "2022",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1689605208/759291_ZAOY5_2387_002_100_0000_Light-Prince-of-Wales-wool-dress.jpg",
    productName: "PRINCE OF WALES WOOL DRESS",
    price: "291394",
    color: "Gray",
    badge: true,
    des: "Gucci rewrites the rulebook for traditional suiting in womenswear. This contemporary dress has been crafted from a Prince of Wales wool, revealing a streamlined construction. The unexpected silhouette is supported by a concealed bustier and defined by an Interlocking G zip puller.",
  },
  {
    _id: "2061",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_1200x1200/1689181278/765507_ZAN3T_1078_002_100_0000_Light-Pinstripe-wool-coat-with-Horsebit.jpg",
    productName: "PINSTRIPE WOOL COAT WITH HORSEBIT",
    price: "291374",
    color: "Dark Gray",
    badge: false,
    des: "The season's sleek silhouette draws inspirations from the 1990s, with slim-fitting tops and slightly low-slung bottoms. The pared-down look has been reinterpreted in a new palette with neutrals and pops of color. Crafted in a grey pinstripe wool, this sophisticated coat is enriched with a slim Horsebit detail and an Interlocking G and heart embroidery.",
  },
  {
    _id: "207",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1681511423/737805_XWAXX_4003_001_100_0000_Light-Childrens-textured-wool-coat.jpg",
    productName: "CHILDREN'S TEXTURED WOOL COAT",
    price: "122403",
    color: "Black",
    badge: false,
    des: "OshKosh B'gosh made its name by designing hickory-striped denim bib overalls in mini dimensions for children. From casual playwear to special occasions, here signature Gucci pieces are emblazoned with the two logos and enriched with playful patches and prints bearing four-leaf clovers and cuddly bears",
  },
  {
    _id: "208",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1681512329/741138_ZAMKZ_4215_001_100_0000_Light-Childrens-wool-single-breasted-coat.jpg",
    productName: "CHILDREN'S WOOL SINGLE-BREASTED COAT",
    price: "99913",
    color: "Black Red",
    badge: true,
    des: "OshKosh B'gosh made its name by designing hickory-striped denim bib overalls in mini dimensions for children. From casual playwear to special occasions, here signature Gucci pieces are emblazoned with the two logos and enriched with playful patches and prints bearing four-leaf clovers and cuddly bears",
  },
  {
    _id: "209",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1681945212/749979_XKDEW_9575_001_100_0000_Light-Childrens-Double-G-wool-cardigan.jpg",
    productName: "CHILDREN'S DOUBLE G WOOL CARDIGAN",
    price: "70335",
    color: "Wool",
    badge: true,
    des: "The Double G motif continues to appear in playful new ways, season after season. This cardigan is crafted from wool jacquard with an all-over geometric monogram motif. One of the House's most recognizable symbols, the Double G connects different chapters of Gucci's history.",
  },
  {
    _id: "210",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1463003120/433148_CPWE0_9075_001_100_0000_Light-Childrens-Ace-leather-sneaker.jpg",
    productName: "CHILDREN'S ACE LEATHER SNEAKER",
    price: "36640",
    color: "White",
    badge: true,
    des: "Presented here with a green leather trim and the House Web in green and red, a reinterpretation of the Ace sneaker that imbues the everlasting qualities of style",
  },
  {
    _id: "211",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1658073610/681374_U4G20_4464_002_100_0000_Light-Childrens-Double-G-ballet-flat.jpg",
    productName: "CHILDREN'S DOUBLE G BALLET FLAT",
    price: "45820",
    color: "White and Black",
    badge: true,
    des: "The House logo continues to enrich collections in contemporary new ways. Here, the Double G appears as part of a geometric cotton motif atop this children's ballet flat.",
  },
  {
    _id: "212",
    img: "https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1682704849/750709_FAB5S_6452_002_100_0000_Light-Childrens-Gucci-Tennis-1977-high-top-sneaker.jpg",
    productName: "CHILDREN'S GUCCI TENNIS 1977 HIGH-TOP SNEAKER",
    price: "50799",
    color: "Pink and White",
    badge: true,
    des: "OshKosh B'gosh made its name by designing hickory-striped denim bib overalls in mini dimensions for children. From casual playwear to special occasions, here signature Gucci pieces are emblazoned with the two logos and enriched with playful patches and prints bearing four-leaf clovers and cuddly bears.",
  },
];
// =================== Gucci data End here ==============
// =================== Dior data Start here ============
export const Dior = [
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/51UMj1QGe-L._SL1500_.jpg",
    productName: "Christian Dior Eau Sauvage Eau De Toilette Bottle",
    price: "16499",
    color: "Wood",
    badge: true,
    des: "Brand: Dior Item Form Spray Item Volume: 200 Millilitres Scent Wood  Special Feature: Travel Size",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/51IAhbeRCAL._SL1000_.jpg",
    productName: "Dior Homme by Christian Dior for Men 3.4 oz Eau de",
    price: "13752",
    color: "Golden",
    badge: false,
    des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 100 Millilitres ,Scent: Lavender, Musk , Fruity, Mint ,Special Feature: Travel Size",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/51vZwMd0pzL._SL1000_.jpg",
    productName: "Christian Dior Dior Homme Eau De Toilette Spray",
    price: "8249",
    color: "White",
    badge: false,
    des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 5 Fluid Ounces ,Scent: Christian Dior Dior Homme Eau De Toilette Spray ,Special Feature: Travel Size",
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/6103VZY7p8L._SL1500_.jpg",
    productName: "Dior Christian Rouge Couture Colour Comfort & Wear Matte Lipstick",
    price: "9499",
    color: "Black",
    badge: false,
    des: "Skin Friendly Ingredients ,Help To Boost Your Appearance ,Gives You Attractive Look Brand: Dior ,Colour: 047 Miss ,Skin Type: All ,Finish Type: Matte ,Coverage: Full ,Age Range (Description): Adult ,Item Weight: 3 Grams ,Item Dimensions LxWxH: 25 x 19 x 76 Millimeters ,Target Audience: Girls ,Package Information: Tube",
  },
  {
    _id: "205",
    img: "https://m.media-amazon.com/images/I/41P70aXyeoL.jpg",
    productName: "Dior Milky Tint Addict, 156 Milky Pastel, 0.18 Ounce Brand: Dior",
    price: "21009",
    color: "Milky Pastel",
    badge: true,
    des: "Easy application ,Suitable for all skin types ,Long lasting ,Sourced from Strawberrynet",
  },
  {
    _id: "206",
    img: "https://m.media-amazon.com/images/I/41LRjRkPXDL.jpg",
    productName: "Dior Addict Lip Maximizer High Volume Lip Plumper Cd NIB 6ml 001 Pink",
    price: "6770",
    color: "Pink",
    badge: false,
    des: "Brand: DIOR ADDICT ,Colour: Pink ,Skin Type: All ,Item Form: Liquid ,Finish Type: Glossy ,Coverage: High ,Age Range (Description): Adult ,Skin Tone: All ,Target Audience: Women, Girls ,Package Information: Tube",
  },
  {
    _id: "207",
    img: "https://m.media-amazon.com/images/I/711NysppfvL._SL1500_.jpg",
    productName: "Christian Dior Women's Miss Dior Blooming Bouquet EDT Spray (New Scent)",
    price: "10049",
    color: "Pink",
    badge: false,
    des: "Brand: Christian Dior ,Item Form: Spray ,Item Volume: 100 Millilitres ,Scent: Dior Miss Dior Blooming ,Special Feature: Travel Size",
  },
  {
    _id: "208",
    img: "https://m.media-amazon.com/images/I/617cIMD0onL._SL1500_.jpg",
    productName: "Dior Poison for Women, 100ml Amber honey berries and spice.",
    price: "17085",
    color: "Black",
    badge: true,
    des: " Poison by Christian Dior EDT spray 100.55ml Design house: Christian Dior Year introduced: 1985 Recommended use: Romantic Brand: Dior ,Item Form: Spray ,Item Volume: 3.4 Fluid Ounces ,Scent: Fresh ,Special Feature: Travel Size",
  },
  {
    _id: "209",
    img: "https://m.media-amazon.com/images/I/41JwXH1M+tL._SL1000_.jpg",
    productName: "Dior Addict by Christian Dior Eau Fraiche Spray 1.7 oz for Women",
    price: "15470",
    color: "White",
    badge: false,
    des: "Eau Fraiche Spray ,Authenic ,Fragrance ,Quality Dior Addict indulges the senses with sumptuous silk tree flower, voluptuous night queen flower, and luscious bourbon vanilla combined with sandalwood and tonka bean to evoke a feeling of passion in the woman who wears it. Sensual. Soft.",
  },
];
// =================== Dior data End here ==============
// =================== Apple data Start here ============
export const Apple = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    productName: "Apple MacBook Air Laptop M2",
    price: "79999",
    color: "Black and White",
    badge: true,
    des: "13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of color ,System on Chip (SoC), Apple M1 chip, 8-core CPU with 4 performance cores and 4 efficiency cores, 16-core Neural Engine",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/71bhWgQK-cL._SL1500_.jpg",
    productName: "Apple AirPods Pro MagSafe Charging Case",
    price: "16990.00",
    color: "White",
    badge: false,
    des: "Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking places sound all around you , Adaptive EQ automatically tunes music to your ears , Three sizes of soft, tapered silicone tips for a customisable fit",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/81IfN-Rw8uL._SL1500_.jpg",
    productName: "New Apple AirPods Max - Silver",
    price: "59900.00",
    color: "Gray",
    badge: false,
    des: "Apple-designed dynamic driver provides high-fidelity audio , Active Noise Cancellation blocks outside noise, so you can immerse yourself in music , Transparency mode for hearing and interacting with the world around you , Spatial audio with dynamic head tracking provides theater-like sound that surrounds you , Computational audio combines custom acoustic design with the Apple H1 chip and software for breakthrough listening experiences , Designed with a knit-mesh canopy and memory foam ear cushions for an exceptional fit.",
  },
  {
    _id: "204",
    img: "https://m.media-amazon.com/images/I/41l6ANEUyPL._SL1144_.jpg",
    productName: "Apple 12W USB Power Adapter (for iPhone, iPad, Apple Watch)",
    price: "1900.00",
    color: "Black",
    badge: false,
    des: "Use this compact and convenient USB-based power adapter to charge your iPhone, iPad, Apple Watch or iPod with Lightning connector at home, on the road or whenever it’s not connected to a computer.You can connect the adapter directly to your device via the Lightning connector.Featuring a compact design, this power adapter offers fast, efficient charging.",
  },
  {
    _id: "205",
    img: "https://m.media-amazon.com/images/I/71YdE55GwjL._SL1500_.jpg",
    productName: "Apple Watch SE (2nd Gen) [GPS 40 mm] Smart Watch Aluminium Case ",
    price: "23999.00",
    color: "Starlight",
    badge: false,
    des: " It works seamlessly with your Apple devices and services. Unlock your Mac automatically. Find your devices with a tap. Apple Watch requires an iPhone 8 or later with the latest iOS version Water resistant to 50 metres. Three finishes. And a redesigned, All the essentials to help you monitor your fitness, keep connected, track your health and stay safe..",
  },
  {
    _id: "206",
    img: "https://m.media-amazon.com/images/I/71L5lSfJIPS._SL1500_.jpg",
    productName: "New Apple AirTag with AirTag is IP67 water and dust resistant",
    price: "3490.00",
    color: "White",
    badge: true,
    des: "Keep track of and find your items alongside friends and devices in the Find My app ,Simple one-tap setup instantly connects AirTag with your iPhone or iPad ,Play a sound on the built-in speaker to help find your things, or just ask Siri for help",
  },
  {
    _id: "207",
    img: "https://m.media-amazon.com/images/I/61QvSXD+InL._SL1500_.jpg",
    productName: "Apple USB-C to Lightning Cable -2m (for iPhone, iPad)",
    price: "2400.00",
    color: "White",
    badge: false,
    des: "Connect your iPhone, iPad or iPod with Lightning connector to your USB-C– or Thunderbolt 3 (USB-C)–enabled Mac for syncing and charging, or to your USB-C–enabled iPad for charging. ,You can also use this cable with your Apple 18W, 20W, 29W, 30W, 61W, 87W or 96W USB‑C Power Adapter to charge your iOS device and even take advantage of the fast-charging feature on selected iPhone and iPad models.",
  },
  {
    _id: "208",
    img: "https://m.media-amazon.com/images/I/81UDF62AqHS._SX522_.jpg",
    productName: "Apple Magic Keyboard for iPad ",
    price: "31900.00",
    color: "Black",
    badge: true,
    des: "The Magic Keyboard is the perfect companion for iPad Pro, now available in two colors.It features a comfortable, responsive typing experience, a trackpad that opens up new ways to work, a USB-C port for charging, backlit keys, and front and back protection.With a floating cantilever design, iPad Pro attaches magnetically and allows you to smoothly adjust to the perfect viewing angle.",
  },
  {
    _id: "209",
    img: "https://m.media-amazon.com/images/I/71L5lSfJIPS._SL1500_.jpg",
    productName: "New Apple AirTag with AirTag is IP67 water and dust resistant",
    price: "3490.00",
    color: "White",
    badge: true,
    des: "Keep track of and find your items alongside friends and devices in the Find My app ,Simple one-tap setup instantly connects AirTag with your iPhone or iPad ,Play a sound on the built-in speaker to help find your things, or just ask Siri for help",
  },
  {
    _id: "210",
    img: "https://m.media-amazon.com/images/I/71GLMJ7TQiL._SL1500_.jpg",
    productName: "Apple iPhone 13 (128GB) - Starlight",
    price: "3490.00",
    color: "Starlight",
    badge: false,
    des: "15 cm (6.1-inch) Super Retina XDR display ,Cinematic mode adds shallow depth of field and shifts focus automatically in your videos ,Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording, 12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording ,A15 Bionic chip for lightning-fast performance",
  },
  {
    _id: "211",
    img: "https://m.media-amazon.com/images/I/61cwywLZR-L._SL1500_.jpg",
    productName: "Apple iPhone 14 (128 GB) - Midnight",
    price: "61999.00",
    color: "Black",
    badge: true,
    des: "15.40 cm (6.1-inch) Super Retina XDR display ,Advanced camera system for better photos in any light ,Cinematic mode now in 4K Dolby Vision up to 30 fps ,Action mode for smooth, steady, handheld videos ,Vital safety technology — Crash Detection calls for help when you can’ ,All-day battery life and up to 20 hours of video playback ,Industry-leading durability features with Ceramic Shield and water resistance",
  },
  {
    _id: "212",
    img: "https://m.media-amazon.com/images/I/71v2jVh6nIL._SL1500_.jpg",
    productName: "Apple iPhone 15 (256 GB) - Pink",
    price: "89900.00",
    color: "Pink",
    badge: true,
    des: " Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can see who’s calling, track your next ride, check your flight status, features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant. The Ceramic Shield front is tougher than any smartphone glass. And the 6.1 Super Retina XDR display is up to 2x brighter in the sun compared to iPhone 14.",
  },
  {
    _id: "213",
    img: "https://m.media-amazon.com/images/I/61YdD9veZXL._SL1500_.jpg",
    productName: "Turtle® Dual Layer Hard Case for Apple iPhone 14 Back Cover ",
    price: "999.00",
    color: "Aqua",
    badge: false,
    des: " TURTLE Case Outside Hard PC + Inside Soft TPU are Provided with Perfect Quality Finish & Precious Cut-Outs for all Ports & Camera. Easy Access of Buttons, Camera, Audio Jack & Charging Ports.TURTLE Case Inside Soft TPU Can Cover The Edges Of Both Side, Covers All Corners, Keep The Phone From Scratching Or Touching The Ground, Durable & Shockproof.",
  },
  {
    _id: "214",
    img: "https://m.media-amazon.com/images/I/515SgB2O-2L._SL1500_.jpg",
    productName: "SQUIF Airtag Case for Apple Airtags Silicone Case Protective Cover ",
    price: "249.00",
    color: "Black",
    badge: false,
    des: "Exclusively Compatible with AirTag (2021) Only. AirTag Device is not included ,Easy to Use with Hook Ring Option, Multi-Purpose, Stylish, Washable, Durable ,Convenient Keychain: With a durable keychain ring, you can easily attach the Airtag Finder to your important items. Bags for kids, keychains for parents, dog leashes, car keys, and more. There's no need to be concerned about losing your location",
  },
  {
    _id: "215",
    img: "https://m.media-amazon.com/images/I/61XCCsBoDgL._SL1500_.jpg",
    productName: "Apple iPhone 14 Pro Max Clear Case with MagSafe ​​​​​​​Protective",
    price: "4990.00",
    color: " Clear",
    badge: true,
    des: " Crafted with a blend of optically clear polycarbonate and flexible materials, the case fits right over the buttons for easy use. On the surface, a scratch-resistant coating has been applied to both the interior and exterior. And all materials and coatings are optimised to prevent yellowing over time.With built-in magnets that align perfectly with iPhone 14 Pro Max, this case offers a magical attach experience and faster wireless charging",
  },
];
// =================== Apple data End here ==============
// =================== Hm data Start here ============
export const HM = [
  {
    _id: "201",
    img: "https://m.media-amazon.com/images/I/71VK4FNxP2L._UL1500_.jpg",
    productName: "BE SAVAGE Letterman Varsity Jacket",
    price: "897",
    color: "Black",
    badge: false,
    des: "Care Instructions: Machine Wash ,Fit Type: Western ,This jackets is very stylish and quite suitable for casual and party wear ,It's stylish design gives you charming look and perfect comfort. ,Our varsity jacket is made of light and soft fabric. Lightweight and stylish, the best active coat for Spring, Fall and Winter season indoor /outdoor wearing.",
  },
  {
    _id: "202",
    img: "https://m.media-amazon.com/images/I/41e4b+XoLML._UX569_.jpg",
    productName: " Blend Standard Length Varsity Jacket",
    price: "742",
    color: "Black",
    badge: true,
    des: "This Be Savage Letterman Unisex Varsity Classic Jacket is fashionable and can be worn on any occasion. It can improve your temperament and make you look handsome. Whether on a cold night or a cool morning, a BE SAVAGE Varsity Jacket will be your best choice. The combination of street fashion and classic baseball jacket makes this bomber jacket even more special！ The jacket has a stand-up collar for more warmth. Two pockets to keep your hands warm.",
  },
  {
    _id: "203",
    img: "https://m.media-amazon.com/images/I/71+FSCCbv2L._UY741_.jpg",
    productName: "Lymio Women's Hoodies || Sweatshirt for Women",
    price: "499",
    color: "Pink",
    badge: false  ,
    des: "Care Instructions: Machine Wash ,Fit Type: Regular ,Women's Hoodies || sweatshirt for Women || Unisex Hoodie ,Actual Products color may vary with product due to monitor settings ,Wash care: machine wash cold, tumble dry low, do not bleach. Check our size chart to get your best fit ,Fit Type: Regular Fit ,Care Instructions: Wash In Cold Water",
  },
  {
    _id: "204",
    img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Ff1%2F97%2Ff1973e0dabdf30d1754178d9bcbd17e28b198f1e.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bkids_boys_clothing_trousersjeans_joggerssweatpants%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
    productName: "Brushed-inside joggers",
    price: "999",
    color: "Light grey marl",
    badge: true,
    des: "Joggers in sweatshirt fabric made from a cotton blend with a soft brushed inside. Covered elastication and a drawstring at the waist, side pockets and ribbed hems.",
  },
  {
    _id: "205",
    img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F61%2Fd5%2F61d5c650f58c8d2ad6801ef124bacbe7f3c38364.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
    productName: "2-piece sweatshirt set",
    price: "1499",
    color: "Green/Brooklyn",
    badge: true,
    des: "Cosy set in lightweight sweatshirt fabric. Long-sleeved top with a round neckline and dropped shoulders. Ribbing around the neckline, cuffs and hem. Bottoms with an elasticated, drawstring waist and ribbed hems.",
  },
  {
    _id: "206",
    img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F14%2Fb8%2F14b8e7c9d6e526620b07e42ba609d36bf0392161.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bkids_boys_clothing_trousersjeans_joggerssweatpants%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
    productName: "3-pack joggers",
    price: "2199",
    color: "Navy blue/Light grey marl",
    badge: true,
    des: "Joggers in soft cotton jersey with an elasticated waist, pockets in the side seams and ribbed hems.",
  },
  {
    _id: "207",
    img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fca%2F8a%2Fca8aef436c1c28b4aec38abc8d65509282ce8c1d.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
    productName: "Flared leggings",
    price: "1299",
    color: "Black",
    badge: false,
    des: "Leggings in jersey. High waist with concealed elastication, and flared legs.",
  },
  {
    _id: "208",
    img: "https://lp2.hm.com/hmgoepprod?set=format%5Bwebp%5D%2Cquality%5B79%5D%2Csource%5B%2Fbc%2F84%2Fbc8490c84b8d9f88ff539b28ce503a54c3c5bc79.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bladies_jeans_loose%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url%5Bfile%3A%2Fproduct%2Fmain%5D",
    productName: "Slim Mom High Ankle Jeans",
    price: "2010",
    color: "Dark denim blue",
    badge: true,
    des: "5-pocket, ankle-length jeans in slightly stretchy denim with an extra-high waist, zip fly and gently tapered legs. Some of the cotton content of the jeans is recycled.",
  },
  {
    _id: "209",
    img: "https://lp2.hm.com/hmgoepprod?set=format%5Bwebp%5D%2Cquality%5B79%5D%2Csource%5B%2F70%2F63%2F7063e2acb982fd03c3d7c0504216a100533d5290.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url%5Bfile%3A%2Fproduct%2Fmain%5D",
    productName: "Short cardigan",
    price: "1499",
    color: "Cream",
    badge: false,
    des: "Short cardigan in a soft rib knit with a V-neckline and buttons down the front. Dropped shoulders and long, gently flared sleeves.",
  },
];
// =================== Hm data End here ==============
// =================== Samsung data Start here ============
export const Samsung = [
  {
    _id: "201",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-s711blgbins/gallery/in-galaxy-s23-fe-s711-479553-sm-s711blgbins-thumb-538355945?imwidth=480",
    productName: "Samsung Galaxy S23 Fe 5G",
    price: "59999",
    color: "Green and White",
    badge: true,
    des: "Nightography's enhanced AI keeps details clear, so low light photos and videos will be bright and colorful from dusk to dawn and back again.",
  },
  {
    _id: "202",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-s911bzkcins/gallery/in-galaxy-s23-s911-sm-s911bzkcins-thumb-535265933?imwidth=480",
    productName: "Galaxy S23",
    price: "79999",
    color: "Black",
    badge: false,
    des: "  The Dynamic AMOLED 2X display with Vision Booster on Galaxy S23 and Galaxy S23+ received a certification from VDE Germany for 100 percent Mobile Color Volume in the DCI-P3 color range, which means your images aren’t washed out and you’ll get unbelievably vivid colors regardless of differing levels of brightness. The display can achieve peak brightness of up to 1750 nits, improving the contrast between dark and light aspects of digital content for a more brilliant picture quality, with a 3,000,000:1 contrast ratio to make your mobile experience more immersive.  Available functions may vary depending on the device, country, region, carrier, or the version of One UI.",
  },
  {
    _id: "203",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/2302/gallery/in-galaxy-s23-s918-sm-s918bzgcins-thumb-534863401?imwidth=480",
    productName: "Galaxy S23 Ultra",
    price: "124999",
    color: "Gray",
    badge: false,
    des: "Typical value tested under third-party laboratory condition. Typical value is the estimated average value considering the deviation in battery capacity among the battery samples tested under IEC 61960 standard. Rated capacity is 3785mAh for Galaxy S23, 4565mAh for Galaxy S23+ and 4855mAh for Galaxy S23 Ultra. Actual battery life may vary depending on network environment, usage patterns and other factors.",
  },
  {
    _id: "204",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-x510nliainu/gallery/in-galaxy-tab-s9-fe-sm-x510-sm-x510nliainu-thumb-538493081?imwidth=480",
    productName: "Galaxy Tab S9 FE",
    price: "36999",
    color: "Pink",
    badge: true,
    des: "Color and model availability may vary depending on country or carrier  The display used in Galaxy Tab S9 FE and Tab S9 FE+ has received the Low Blue Light certification from SGS based on its ability to reduce some of the blue light emission from the screen. More information of this certification can be found on www.sgs.com/performance  Blue light certification target is under 9.9% (test from SGS)  Typical value tested under third-party laboratory conditions. Typical value is the estimated average value considering the deviation in battery capacity among the battery samples tested under IEC 61960 standard. Rated (minimum) capacity is 8,000 mAh for Galaxy Tab S9 FE and 10,090 mAh for Galaxy Tab S9 FE+. Actual battery life may vary depending on network environment, usage patterns and other factors  15W Fast Charging is supported when the Galaxy Tab S9 FE and Tab S9 FE+'s display is turned off and the battery level is at least 30%",
  },
  {
    _id: "205",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/ww80t504dab-tl/gallery/in-front-loading-washer-ww10t534daws1-374541-ww80t504dab-tl-383418964?$1300_1038_PNG$",
    productName: "8.0 kg Ecobubble™ Front Load Washing Machine ",
    price: "42000",
    color: "Black",
    badge: false,
    des: "Enjoy efficient cleaning, even at low temperatures* with Eco Bubble™ technology. Detergent is turned into bubbles, so it quickly penetrates fabric and removes dirt easily, while saving energy and protecting its color and texture**.",
  },
  {
    _id: "206",
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/wa10bg4686brtl/gallery/in-wa4000b-435227-wa10bg4686brtl-533661234?$1300_1038_PNG$",
    productName: "9.0 kg Ecobubble™ Upper Load Washing Machine",
    price: "29300",
    color: "Gray",
    badge: false,
    des: "Give your laundry an intensive and hygienic cleaning with hot water and steam. The Hygiene Steam wash cycle washes clothes at 60°C to eliminate 99.9% of bacteria** and remove stubborn and oily stains***.",
  },
  {
    _id: "207",
    img: "https://m.media-amazon.com/images/I/81tusZvwFGL._SX679_.jpg",
    productName: "Samsung Galaxy M34 5G",
    price: "18499",
    color: "Silver",
    badge: false,
    des: "16.42 Centimeters (6.5-Inch) Super AMOLED Display, FHD+ Resolution, 1080 x 2340 Pixels Protected by Corning Gorilla Glass 5 ,50MP+8MP+2MP Triple Camera Setup - True 50MP No Shake Cam (F1.8) Main Camera + 8MP (F2.2) + 2MP (F2.4)| 13MP (F2.0) Front Camera",
  },
  {
    _id: "208",
    img: "https://m.media-amazon.com/images/I/8155EFAxDzL._SX679_.jpg",
    productName: "Samsung Galaxy M14 5G",
    price: "11990",
    color: "Green",
    badge: false,
    des: "Superfast 5G with 13 5G Bands, Powerful Exynos 1330 Octa Core 2.4GH 5nm processor with latest Android 13 having One UI 5.0 interface ,50MP+2MP+2MP Triple camera setup- True 50MP (F1.8) main camera + 2MP (F2.4) + 2MP (F2.4)| 13MP (F2.0) front camera",
  },
  {
    _id: "209",
    img: "https://m.media-amazon.com/images/I/41kg-+XWoxL._SY300_SX300_.jpg",
    productName: "Samsung Galaxy M04 Blue",
    price: "6499",
    color: "Dark Blue",
    badge: false,
    des: "Powerful MediaTek Helio P35 Octa Core 2.3GHz with Android 12,One UI Core 4.1 13MP+2MP Dual camera setup- True 13MP (F2.2) main camera + 2MP (F2.4) | 5MP (F2.2) front came 16.55 centimeters (6.5-inch) LCD, HD+ resolution with 720 x 1600 pixels resolution, 269 PPI with 16M color",
  },
  {
    _id: "210",
    img: "https://m.media-amazon.com/images/I/61vN1isnThL._SX679_.jpg",
    productName: "Samsung Galaxy S20 FE 5G",
    price: "29999",
    color: "Dark Blue",
    badge: false,
    des: "5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM ,Triple Rear Camera Setup - 12MP (Dual Pixel) OIS F1.8 Wide Rear Camera + 8MP OIS Tele Camera + 12MP Ultra Wide | 30X Space Zoom, Single Take & Night Mode | 32MP F2.2 Front Punch Hole Camera",
  },
  {
    _id: "211",
    img: "https://m.media-amazon.com/images/I/41op1vdp-UL._SX300_SY300_QL70_FMwebp_.jpg",
    productName: "Samsung Galaxy M13",
    price: "9199",
    color: "Light Green",
    badge: false,
    des: "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase ,Upto 12GB RAM with RAM Plus | 64GB internal memory expandable up to 1TB| Dual Sim (Nano)",
  },
  {
    _id: "212",
    img: "https://m.media-amazon.com/images/I/61kAlJyn7QL._SX679_.jpg",
    productName: "Samsung Galaxy A34 5G",
    price: "27999",
    color: "Black",
    badge: false,
    des: "48MP(OIS)+8MP+5MP Triple camera setup - 48MP (F1.8) Main Camera with OIS + 8MP (F2.2) Ultra wide camera + 5MP (F2.4) depth camera | 13MP (F2.2) front camera 16.65 centimeters (6.6-inch) FHD+ Super AMOLED display, FHD+ resolution with 1080 x 2340 pixels , 393 PPI with 16M colours Android 13, v13.0 operating system with MediaTek | MTK D1080 2.6GHz,2GHz Octa-Core processor",
  },
  {
    _id: "213",
    img: "https://m.media-amazon.com/images/I/71UCpBBIfaL._SX679_.jpg",
    productName: "Samsung Galaxy Watch4 Bluetooth",
    price: "11990",
    color: "Black",
    badge: false,
    des: "Only compatible with Android Smartphones (Runs on Wear OS Powered by Samsung) Bioelectrical Impedance Analysis Sensor for Body Composition Analysis, Optical Heart Rate Sensor.Health Monitoring features such as Advanced Sleep Analysis & Women's Health.",
  },
  {
    _id: "214",
    img: "https://m.media-amazon.com/images/I/61mkpp+F95L._SX522_.jpg",
    productName: "Samsung Galaxy Watch4 Classic LTE (4.6cm, Black)",
    price: "17799",
    color: "White",
    badge: false,
    des: "nly compatible with Android Smartphones (Runs on Wear OS Powered by Samsung) Bioelectrical Impedance Analysis Sensor for Body Composition Analysis, Optical Heart Rate Sensor. Health Monitoring features such as Advanced Sleep Analysis & Women's Health. Enhanced Fitness tracking lets you track 90+ workouts; Enriched App availability and connectivity with Wear OS, Powered by Samsung Included Components: ‎Galaxy Watch::Watch Strap::Wireless Charger::Quick Start Quide; Connectivity Technology: Usb; Item Type Name: Smart Watch",
  },
  {
    _id: "215",
    img: "https://m.media-amazon.com/images/I/61XmNBJTyNL._SX679_.jpg",
    productName: "Samsung Galaxy Watch5 Bluetooth ",
    price: "19999",
    color: "Purple",
    badge: false,
    des: "Sleep Tracking: Know your sleep with our new and improved sleep tracking technology. Plan your bedtime, detect snoring, understand and track your sleep. ,Body composition Analysis (BIA Measurement): Monitor everything from body fat percentage (BIA) to skeletal muscle weight. All the feedback you need to track your progress.",
  },
];
// =================== Samsung data End here ==============